image:
  file: .gitpod.Dockerfile
 
tasks:
  - name: MySQL Server 
    init: |
      docker pull mysql:8.0
    command: | 
      docker-compose down -v && docker-compose up -d
      docker ps
    openMode: split-left
  - name: MySQL Client 
    command: |
      mysql --version
    openMode: split-right
  - name: My Work 
    command: |
      date
    openMode: tab-after  
ports:
  - port: 3306
    visibility: public
    onOpen: ignore
