version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '#skcc06433'
      MYSQL_DATABASE: devdb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: '#skcc06433'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
volumes:
  mysql_data:

