# ===============================================================
# 공통 설정 (Default Profile)
# 모든 프로필에 기본으로 적용되는 설정입니다.
# 특정 프로필에서 재정의하지 않는 한, 이 설정이 사용됩니다.
# ===============================================================
server:
  port: 8081 # 내장 웹 서버(Tomcat)가 사용할 포트 번호입니다.
  servlet:
    #context-path: /api # 애플리케이션의 기본 URL 경로(Context Path)를 설정합니다. (예: http://localhost:8081/api)
    encoding:
      charset: UTF-8   # 모든 HTTP 요청 및 응답의 기본 문자 인코딩을 UTF-8로 설정합니다.
      enabled: true    # 서블릿 인코딩 설정을 활성화합니다.
      force: true      # 요청과 응답에 항상 설정된 인코딩을 강제로 적용합니다.
  compression: # HTTP 응답 압축 설정
    enabled: true # 응답 본문을 GZIP으로 압축하여 네트워크 트래픽을 줄입니다.
    min-response-size: 2048 # 압축을 적용할 최소 응답 크기입니다. (단위: bytes)
    mime-types: application/json,text/html,text/xml,text/plain # 압축을 적용할 미디어 타입 목록입니다.

spring:
  profiles:
    active: dev # 현재 활성화된 프로필을 'dev'로 설정합니다.

jasypt:
  encryptor:
    password: jasyptStringEncryptor
